version: '3'

services:
  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus-go-basic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres: