version: '3'

services:
  migrates:
    build:
      context: .
      dockerfile: docker/goose/Dockerfile
    depends_on:
      - postgres
    command: >
      sh -c "sleep 5 &&
      goose -dir migrations postgres 'postgres://user:password@postgres:5432/postgres?sslmode=disable' up"
    networks:
      - go-net
  go-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - migrates
    ports:
      - "8080:8080"
    networks:
      - go-net
  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus-go-basic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - go-net
networks:
  go-net:
#    driver: bridge

volumes:
  postgres: