name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Установка необходимой версии Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.14' # Автоматически выбирает последнюю версию >=1.14
      id: go

    # Запуск golangci-lint (последняя версия)
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m

    # Запуск юнит-тестов
    - name: Run unit tests
      run: go test -race -count=100 -v ./...

    # Сборка бинарного файла
    - name: Build binary
      run: go build -o service_binary .
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64
